### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by 594zyc** [qumengxue/RIO#1]
Hi,

Thanks for releasing this great dataset! I have downloaded the annotations in COCO format, but do not find the intention description with the object category replaced. Is there a script to do this? Thanks

Best

**Comment by qumengxue** [comment]
> Hi,
> 
> 
> 
> Thanks for releasing this great dataset! I have downloaded the annotations in COCO format, but do not find the intention description with the object category replaced. Is there a script to do this? Thanks
> 
> 
> 
> Best

Oh yes! I will update the script and the bare format data (intention without category) soon! Thanks for your attention!

**Comment by qumengxue** [comment]
> > Hi,
> > Thanks for releasing this great dataset! I have downloaded the annotations in COCO format, but do not find the intention description with the object category replaced. Is there a script to do this? Thanks
> > Best
> 
> Oh yes! I will update the script and the bare format data (intention without category) soon! Thanks for your attention!

Updated to https://drive.google.com/drive/folders/1IAvh8tBGS3WWgV4SbVoqhwCkmyoSFffh?usp=drive_link
